{
 "title": "Quiche",
 "tags": "nesquic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput With Varying Connection Delay",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic\" and r._field == \"throughput\")\n  |> filter(fn: (r) => r.library == \"quiche\")"
    }
   ]
  },
  { "title": "Unbounded", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "This experiment runs the client and server in a separate network namespace, but does alter their traffic in any way."
   }
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"unbounded\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"unbounded\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"unbounded\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"unbounded\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"unbounded\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"unbounded\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"unbounded\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"unbounded\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  { "title": "5ms Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 72 },
   "options": {
    "content": "This experiment delays all traffic by 5ms."
   }
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 88 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"delay5\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 88 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"delay5\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"delay5\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"delay5\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"delay5\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"delay5\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 96 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"delay5\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 96 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"delay5\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  { "title": "20ms Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 120 },
   "options": {
    "content": "This experiment delays all traffic by 20ms."
   }
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 136 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"delay20\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 136 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"delay20\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 128 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"delay20\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 128 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"delay20\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 152 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"delay20\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 152 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"delay20\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 144 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"delay20\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 144 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"delay20\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  { "title": "Driving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 168 },
   "options": {
    "content": "This experiment simulates a cell phone that is connected to an LTE network while driving. 50ms delay are applied to the traffic."
   }
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 184 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"driving\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 184 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"driving\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 176 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"driving\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 176 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"driving\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 200 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"driving\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Data Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 12.0, "y": 200 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"volume_kb_sum\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"driving\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Server I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 192 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"server\" and r.job == \"driving\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Client I/O Syscalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12.0, "x": 0, "y": 192 },
   "targets": [
    {
     "query": "from(bucket: \"nesquic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nesquic_io\" and r._field == \"count\")\n  |> filter(fn: (r) => r.library == \"quiche\" and r.mode == \"client\" and r.job == \"driving\")\n  |> keep(columns: [\"_time\", \"_value\", \"syscall\"])\n  |> rename(columns: {\"_value\": \"count\"})\n  |> group()"
    }
   ]
  }
 ]
}